### ISSUE TITLE
Starting development server

### ISSUE THREAD

**Issue by fikremariamasmro** [element-plus/vue-cli-plugin-element-plus#1]
> test@0.1.0 serve /home/fkl/Documents/test
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                               3:03:12 PM

This dependency was not found:

* element-plus/lib/locale/lang/en in ./src/plugins/element.js

To install it, you can run: npm install --save element-plus/lib/locale/lang/en
(node:72992) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img'
(node:72992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:72992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:72992) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img.old'
(node:72992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:72992) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz'
(node:72992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:72992) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz.old'
(node:72992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
^C

**Comment by zazzaz** [comment]
it is true that we have some problem with locale import, you can skip loading locale ATM, and we will fix it soon on element plus

**Comment by fikremariamasmro** [comment]
> it is true that we have some problem with locale import, you can skip loading locale ATM, and we will fix it soon on element plus

Ok,
