### ISSUE TITLE
在ts模式下导致main.ts文件错乱且没有相关类型定义

### ISSUE THREAD

**Issue by ym87498510** [element-plus/vue-cli-plugin-element-plus#2]
```typescript
import router from './router'
import store from './store'
import installElementPlus from './plugins/element.js'
installElementPlus(app)
app.mount('#app')

createApp(App).use(store).use(router).mount('#app')
```
这里生成的文件依旧是js文件： ./plugins/element.js

错误
ERROR in src/main.ts:8:11
TS2304: Cannot find name 'App'.
    6 | app.mount('#app')
    7 | 
  > 8 | createApp(App).use(store).use(router).mount('#app')

ERROR in src/main.ts:6:32
TS7016: Could not find a declaration file for module './plugins/element.js'. '/Users/yangm/test/plus-demo/src/plugins/element.js' implicitly has an 'any' type.
    4 | import store from './store'
    5 | // eslint-disable-next-line
  > 6 | import installElementPlus from './plugins/element.js'
      |                                ^^^^^^^^^^^^^^^^^^^^^^
    7 | const app = createApp(App)
    8 | installElementPlus(app)
    9 | app.mount('#app')

**Comment by zazzaz** [comment]
the plugin does not support TS project at the moment.

But will support soon.

At present, you may change the file name to .ts yourself

**Comment by ym87498510** [comment]
Ok,got it,目前手动改成ts，element-plus也会有不少问题，大多提示缺少类型定义，静待支持

**Comment by zazzaz** [comment]
If there's any problem related element plus, feel free to open an issue here https://github.com/element-plus/element-plus/issues/new

**Comment by kid1412621** [comment]
> the plugin does not support TS project at the moment.
> 
> But will support soon.
> 
> At present, you may change the file name to .ts yourself

dude, half 2021 passed

**Comment by kid1412621** [comment]
> Ok,got it,目前手动改成ts，element-plus也会有不少问题，大多提示缺少类型定义，静待支持

修改为 ts 后，还要改 `import * as locale from "element-plus/lib/locale"`
