### ISSUE TITLE
typscript vue3 无法找到声明文件？？

### ISSUE THREAD

**Issue by JerryWang24** [element-plus/vue-cli-plugin-element-plus#9]
无法找到模块“./plugins/element”的声明文件。“e:/workspace/other/cd-open-api-vue3ts/src/plugins/element.js”隐式拥有 "any" 类型。ts(7016)

运行就报这个错误~

**Comment by MinWest** [comment]
怎么解决这个问题的

**Comment by MinWest** [comment]
@JerryWang24
